### ISSUE TITLE
Problems on the FrontEnd example

### ISSUE THREAD

**Issue by jresende** [osu-crypto/batchDualEx#4]
Hi. I'm testing the program, however, when I try to change the circuit file: 
```

./bin/frontend.exe -r 0 -v -f ./circuits/comparison.txt & 
...
reading circuits: ./circuits/AES-non-expanded.txt
...

./bin/frontend.exe -r 1 -v -f ./circuits/comparison.txt 
role: 1  numExe:128  bucketSize:4  numOpen:0  ConcurrentSetups:4  ConcurrentEvals:1  numThreadsPerEval:4
reading circuits: ./circuits/AES-non-expanded.txt
...
```

It doesn't work, because remains the circuit: "./circuits/AES-non-expanded.txt"

Also, I want to ask how can I print the output (the result) of the computation for both parties.

Thanks.

**Comment by ladnir** [comment]
That does appear to be a bug. I'm afk for a couple days. In the mean time it should be easy enough for you to debug. Or I can fix it on Wednesday.

**Comment by ladnir** [comment]
The actor.execute(...) call in the main.cpp file returns a BitVector containing the output. You can print that with std::cout

**Comment by ladnir** [comment]
This is an issue (feature?) with the third party command line parser that i used on this project. It requires that each command line switch have a value. Above you did 

` ... -v -f ./circuit/...`

so the code thought that the `-v` option should have the value `-f ./circuit/...`.

You need to say something like `-v true -f ./circuit/...`

**Comment by jresende** [comment]
Thanks I solved the problem with that ;)

best
João
